stages:
  - build
  - test

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE/test-runner
  AUTOMATION_FRAMEWORK_PATH: "/app/automation_framework"

build_image:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - echo "Список файлов в рабочей директории:"
    - ls -l
    - echo "Проверяем Dockerfile:"
    - ls -l Dockerfile || echo "Dockerfile не найден"
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA


run_tests:
  stage: test
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker pull $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker run --rm $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
