stages:
  - test

run_pytest:
  stage: test
  image: python:3.10
  only:
    - abobatests
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest test-selenium/tests --alluredir=allure-results
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - allure-results
test_runner:
  script:
    - echo "Я жив!"
