stages:
  - build
  - test

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE/test-runner
  AUTOMATION_FRAMEWORK_PATH: "/app/automation_framework"

build_image:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - echo "Список файлов в рабочей директории:"
    - ls -l
    - echo "Проверяем Dockerfile:"
    - ls -l Dockerfile || echo "Dockerfile не найден"
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA

run_tests:
  stage: test
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker pull $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker run --rm \
      -v $CI_PROJECT_DIR/allure-results:/projects/allure-results \
      -e PYTHONPATH=/projects \
      $IMAGE_NAME:$CI_COMMIT_SHORT_SHA \
      sh -c "pytest --alluredir=allure-results"
  artifacts:
      paths:
        - allure-results
  rules:
    # Запускается только при создании или обновлении merge request
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
allure_report:
  stage: test
  image: alpine:latest
  before_script:
    - apk add --no-cache curl unzip openjdk17
    - curl -L -o allure.zip https://github.com/allure-framework/allure2/releases/download/2.34.0/allure-2.34.0.zip
    - unzip allure.zip -d /opt/
    - ln -s /opt/allure-2.34.0/bin/allure /usr/bin/allure
  script:
    - allure generate allure-results -o allure-report --clean
  artifacts:
    paths:
      - allure-report