stages:
  - build
  - test
  - report

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE/test-runner
  AUTOMATION_FRAMEWORK_PATH: "/app/automation_framework"

build_image:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - echo "Список файлов в рабочей директории:"
    - ls -l
    - echo "Проверяем Dockerfile:"
    - ls -l Dockerfile || echo "Dockerfile не найден"
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA

run_tests:
  stage: test
  image: python:3.10-slim
  script:
    - apt-get update && apt-get install -y curl unzip
    - pip install --no-cache-dir pytest allure-pytest
    - pytest tests --alluredir=allure-results
  artifacts:
    paths:
      - allure-results


report:
  stage: report
  image: openjdk:17-slim
  script:
    - apt-get update && apt-get install -y unzip curl
    - curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.34.0/allure-2.34.0.zip
    - unzip allure.zip -d /opt/
    - ln -s /opt/allure-2.34.0/bin/allure /usr/bin/allure
    - allure generate allure-results --clean -o allure-report
    - echo "Отчёт Allure успешно сгенерирован."
  artifacts:
    paths:
      - allure-report





