# Базовый образ
FROM python:3.11-slim

# Установка зависимостей
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем исходный код и тесты
COPY . .

# Команда по умолчанию
CMD ["pytest"]
